### ISSUE TITLE
Improving support requirements

### ISSUE THREAD

**Issue by jpmrodrigues** [Vidasoft-app/adaptador-snorkel-a-epi#1]
Hi,

First of all, thanks for the effort.

I'm trying to print this part but it has some support requirements that I think can be mitigated. Namely the guides on the top part could start with a 45º gradient.

Also, please remove the text since it takes time, needs support and only adds texture which is bad for particle retention.

Again, thanks :)

**Comment by Vidasoft-app** [comment]
Hi,

Thanks a lot for your comments.

I've shared the message with David. He is the one who knows about 3D printing and made the files.

He told me that the print is made without supports.

He also gave me more information about the printing specs:

* 0.4 Extrusor (it's the standard one)
* Extrusor temperature 210°C
* Bed 50
* PLA material (the one we use)

I have updated the README.md file to add these specs.

if you need to modify the font. You have the files available [here](https://github.com/Vidasoft-app/mascaras-3d-coronavirus-protocas3d/tree/master/Archivos%203D%20editables%20conector%20a%20filtro%20Version%204).

Thanks
